version: 0.2

phases:

  install:
    runtime-versions: 
      dotnet: 2.2
    commands:
      - echo "Entering Install Phase"

  build:
    commands:
      - dotnet restore dotnet-core-tutorial.csproj
      - dotnet build dotnet-core-tutorial.csproj
      - dotnet publish dotnet-core-tutorial.csproj -o site
      - cd site
#      - ls -al
      - zip ../site.zip *
      - cd ../
      - mkdir staging
      - mv aws-windows-deployment-manifest.json site.zip staging/
      - cd staging
      - ls -al
artifacts:
  files:
    - '**/*'
  base-directory: 'staging'
